/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_matrix_tests.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

START_TEST(create_matrix_1_OK) {
  matrix_t test_matrix;
  int value_return_test = s21_create_matrix(3, 3, &test_matrix);
  ck_assert_int_eq(value_return_test, OK);
  s21_remove_matrix(&test_matrix);
}
END_TEST

START_TEST(create_matrix_2_wrong_size_1) {
  matrix_t test_matrix;
  int value_return_test = s21_create_matrix(0, 0, &test_matrix);
  ck_assert_int_eq(value_return_test, MATRIX_ERROR);
}
END_TEST

START_TEST(create_matrix_3_wrong_size_2) {
  matrix_t test_matrix;
  int value_return_test = s21_create_matrix(-5, -5, &test_matrix);
  ck_assert_int_eq(value_return_test, MATRIX_ERROR);
}
END_TEST

START_TEST(create_matrix_4_edge_values) {
  matrix_t test_matrix;
  int value_return_test = s21_create_matrix(1, 1, &test_matrix);
  ck_assert_int_eq(value_return_test, OK);
  s21_remove_matrix(&test_matrix);
}
END_TEST

START_TEST(remove_matrix_1) {
  matrix_t test_matrix;
  int value_return_test = s21_create_matrix(3, 4, &test_matrix);
  ck_assert_int_eq(value_return_test, OK);
  ck_assert_int_eq(test_matrix.rows, 3);
  ck_assert_int_eq(test_matrix.columns, 4);
  s21_remove_matrix(&test_matrix);
  ck_assert_int_eq(test_matrix.rows, 0);
  ck_assert_int_eq(test_matrix.columns, 0);
}
END_TEST

START_TEST(eq_matrix_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  s21_create_matrix(3, 4, &test_matrix_1);
  s21_create_matrix(3, 4, &test_matrix_2);
  test_matrix_1.matrix[0][0] = 1.5;
  test_matrix_2.matrix[0][0] = 1.5;
  test_matrix_1.matrix[1][2] = 3.2;
  test_matrix_2.matrix[1][2] = 3.2;
  int return_value = s21_eq_matrix(&test_matrix_1, &test_matrix_2);
  ck_assert_int_eq(return_value, SUCCESS);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
}
END_TEST

START_TEST(eq_matrix_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  s21_create_matrix(3, 4, &test_matrix_1);
  s21_create_matrix(3, 4, &test_matrix_2);
  test_matrix_1.matrix[0][0] = 1.5;
  test_matrix_2.matrix[0][0] = 1.5;
  test_matrix_1.matrix[1][2] = 3.2;
  test_matrix_2.matrix[2][2] = 3.2;
  int return_value = s21_eq_matrix(&test_matrix_1, &test_matrix_2);
  ck_assert_int_eq(return_value, FAILURE);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
}
END_TEST

START_TEST(eq_matrix_3) {
  matrix_t test_matrix_1;
  matrix_t *test_matrix_2 = NULL;
  s21_create_matrix(1, 4, &test_matrix_1);
  int return_value = s21_eq_matrix(&test_matrix_1, test_matrix_2);
  ck_assert_int_eq(return_value, FAILURE);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(sum_matrix_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  matrix_t test_matrix_4;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(3, 3, &test_matrix_2);
  s21_create_matrix(3, 3, &test_matrix_3);
  s21_create_matrix(3, 3, &test_matrix_4);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  test_matrix_2.matrix[0][0] = 1.0;
  test_matrix_2.matrix[0][1] = 0.0;
  test_matrix_2.matrix[0][2] = 0.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 0.0;
  test_matrix_2.matrix[1][2] = 0.0;
  test_matrix_2.matrix[2][0] = 3.0;
  test_matrix_2.matrix[2][1] = 4.0;
  test_matrix_2.matrix[2][2] = 1.0;

  test_matrix_3.matrix[0][0] = 2.0;
  test_matrix_3.matrix[0][1] = 2.0;
  test_matrix_3.matrix[0][2] = 3.0;
  test_matrix_3.matrix[1][0] = 2.0;
  test_matrix_3.matrix[1][1] = 4.0;
  test_matrix_3.matrix[1][2] = 5.0;
  test_matrix_3.matrix[2][0] = 3.0;
  test_matrix_3.matrix[2][1] = 4.0;
  test_matrix_3.matrix[2][2] = 7.0;

  int sum_return_value =
      s21_sum_matrix(&test_matrix_1, &test_matrix_2, &test_matrix_4);
  int return_value = s21_eq_matrix(&test_matrix_4, &test_matrix_3);
  ck_assert_int_eq(return_value, SUCCESS);
  ck_assert_int_eq(sum_return_value, OK);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
  s21_remove_matrix(&test_matrix_4);
}
END_TEST

START_TEST(sum_matrix_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_2);
  s21_create_matrix(2, 2, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  test_matrix_2.matrix[0][0] = 1.0;
  test_matrix_2.matrix[0][1] = 0.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 0.0;

  int sum_return_value =
      s21_sum_matrix(&test_matrix_1, &test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(sum_return_value, CALC_ERROR);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(sum_matrix_3) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  int sum_return_value = s21_sum_matrix(&test_matrix_1, NULL, &test_matrix_3);
  ck_assert_int_eq(sum_return_value, MATRIX_ERROR);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(sub_matrix_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  matrix_t test_matrix_4;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(3, 3, &test_matrix_2);
  s21_create_matrix(3, 3, &test_matrix_3);
  s21_create_matrix(3, 3, &test_matrix_4);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  test_matrix_2.matrix[0][0] = 1.0;
  test_matrix_2.matrix[0][1] = 0.0;
  test_matrix_2.matrix[0][2] = 0.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 0.0;
  test_matrix_2.matrix[1][2] = 0.0;
  test_matrix_2.matrix[2][0] = 3.0;
  test_matrix_2.matrix[2][1] = 4.0;
  test_matrix_2.matrix[2][2] = 1.0;

  test_matrix_3.matrix[0][0] = 0.0;
  test_matrix_3.matrix[0][1] = 2.0;
  test_matrix_3.matrix[0][2] = 3.0;
  test_matrix_3.matrix[1][0] = -2.0;
  test_matrix_3.matrix[1][1] = 4.0;
  test_matrix_3.matrix[1][2] = 5.0;
  test_matrix_3.matrix[2][0] = -3.0;
  test_matrix_3.matrix[2][1] = -4.0;
  test_matrix_3.matrix[2][2] = 5.0;

  int sum_return_value =
      s21_sub_matrix(&test_matrix_1, &test_matrix_2, &test_matrix_4);
  int return_value = s21_eq_matrix(&test_matrix_4, &test_matrix_3);
  ck_assert_int_eq(return_value, SUCCESS);
  ck_assert_int_eq(sum_return_value, OK);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
  s21_remove_matrix(&test_matrix_4);
}
END_TEST

START_TEST(sub_matrix_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_2);
  s21_create_matrix(2, 2, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  test_matrix_2.matrix[0][0] = 1.0;
  test_matrix_2.matrix[0][1] = 0.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 0.0;

  int sum_return_value =
      s21_sub_matrix(&test_matrix_1, &test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(sum_return_value, CALC_ERROR);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(sub_matrix_3) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[2][0] = 0.0;
  test_matrix_1.matrix[2][1] = 0.0;
  test_matrix_1.matrix[2][2] = 6.0;

  int sum_return_value = s21_sub_matrix(&test_matrix_1, NULL, &test_matrix_3);
  ck_assert_int_eq(sum_return_value, MATRIX_ERROR);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(mult_number_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  double num = 2.0;
  s21_create_matrix(2, 2, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_2);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[1][0] = 3.0;
  test_matrix_1.matrix[1][1] = 4.0;

  test_matrix_2.matrix[0][0] = 2.0;
  test_matrix_2.matrix[0][1] = 4.0;
  test_matrix_2.matrix[1][0] = 6.0;
  test_matrix_2.matrix[1][1] = 8.0;

  int mult_num_return_value =
      s21_mult_number(&test_matrix_1, num, &test_matrix_3);
  int eq = s21_eq_matrix(&test_matrix_3, &test_matrix_2);
  ck_assert_int_eq(mult_num_return_value, OK);
  ck_assert_int_eq(eq, SUCCESS);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(mult_number_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  double num = -2.0;
  s21_create_matrix(2, 2, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_2);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[1][0] = 3.0;
  test_matrix_1.matrix[1][1] = 4.0;

  test_matrix_2.matrix[0][0] = -2.0;
  test_matrix_2.matrix[0][1] = -4.0;
  test_matrix_2.matrix[1][0] = -6.0;
  test_matrix_2.matrix[1][1] = -8.0;

  int mult_num_return_value =
      s21_mult_number(&test_matrix_1, num, &test_matrix_3);
  int eq = s21_eq_matrix(&test_matrix_3, &test_matrix_2);
  ck_assert_int_eq(mult_num_return_value, OK);
  ck_assert_int_eq(eq, SUCCESS);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(mult_number_3) {
  matrix_t *test_matrix_1 = NULL;
  matrix_t test_matrix_2;
  matrix_t *test_matrix_3 = NULL;
  double num = 2.0;
  s21_create_matrix(2, 2, &test_matrix_2);

  test_matrix_2.matrix[0][0] = -2.0;
  test_matrix_2.matrix[0][1] = -4.0;
  test_matrix_2.matrix[1][0] = -6.0;
  test_matrix_2.matrix[1][1] = -8.0;

  int mult_num_return_value =
      s21_mult_number(test_matrix_1, num, test_matrix_3);
  int eq = s21_eq_matrix(test_matrix_3, &test_matrix_2);
  ck_assert_int_eq(mult_num_return_value, MATRIX_ERROR);
  ck_assert_int_eq(eq, FAILURE);
  s21_remove_matrix(&test_matrix_2);
}
END_TEST

START_TEST(mult_matrix_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  matrix_t test_matrix_4;

  s21_create_matrix(2, 2, &test_matrix_1);
  s21_create_matrix(2, 2, &test_matrix_2);
  s21_create_matrix(2, 2, &test_matrix_4);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[1][0] = 3.0;
  test_matrix_1.matrix[1][1] = 4.0;

  test_matrix_2.matrix[0][0] = 4.0;
  test_matrix_2.matrix[0][1] = 3.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 1.0;

  test_matrix_4.matrix[0][0] = 8.0;
  test_matrix_4.matrix[0][1] = 5.0;
  test_matrix_4.matrix[1][0] = 20.0;
  test_matrix_4.matrix[1][1] = 13.0;

  int res = s21_mult_matrix(&test_matrix_1, &test_matrix_2, &test_matrix_3);

  int eq = s21_eq_matrix(&test_matrix_3, &test_matrix_4);
  ck_assert_int_eq(res, OK);
  ck_assert_int_eq(eq, SUCCESS);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
  s21_remove_matrix(&test_matrix_4);
}
END_TEST

START_TEST(mult_matrix_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t *test_matrix_3 = NULL;
  matrix_t test_matrix_4;

  s21_create_matrix(2, 2, &test_matrix_1);
  s21_create_matrix(4, 4, &test_matrix_2);
  s21_create_matrix(4, 4, &test_matrix_4);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[1][0] = 3.0;
  test_matrix_1.matrix[1][1] = 4.0;

  test_matrix_2.matrix[0][0] = 4.0;
  test_matrix_2.matrix[0][1] = 3.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 1.0;

  test_matrix_4.matrix[0][0] = 8.0;
  test_matrix_4.matrix[0][1] = 5.0;
  test_matrix_4.matrix[1][0] = 20.0;
  test_matrix_4.matrix[1][1] = 13.0;

  int res = s21_mult_matrix(&test_matrix_1, &test_matrix_2, test_matrix_3);

  int eq = s21_eq_matrix(test_matrix_3, &test_matrix_4);
  ck_assert_int_eq(res, CALC_ERROR);
  ck_assert_int_eq(eq, FAILURE);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_4);
}
END_TEST

START_TEST(mult_matrix_3) {
  matrix_t *test_matrix_1 = NULL;
  matrix_t test_matrix_2;
  matrix_t *test_matrix_3 = NULL;
  matrix_t test_matrix_4;

  s21_create_matrix(4, 4, &test_matrix_2);
  s21_create_matrix(4, 4, &test_matrix_4);

  test_matrix_2.matrix[0][0] = 4.0;
  test_matrix_2.matrix[0][1] = 3.0;
  test_matrix_2.matrix[1][0] = 2.0;
  test_matrix_2.matrix[1][1] = 1.0;

  test_matrix_4.matrix[0][0] = 8.0;
  test_matrix_4.matrix[0][1] = 5.0;
  test_matrix_4.matrix[1][0] = 20.0;
  test_matrix_4.matrix[1][1] = 13.0;

  int res = s21_mult_matrix(test_matrix_1, &test_matrix_2, test_matrix_3);

  int eq = s21_eq_matrix(test_matrix_3, &test_matrix_4);
  ck_assert_int_eq(res, MATRIX_ERROR);
  ck_assert_int_eq(eq, FAILURE);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_4);
}
END_TEST

START_TEST(transpose_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 2, &test_matrix_1);
  s21_create_matrix(2, 3, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 4.0;
  test_matrix_1.matrix[1][0] = 2.0;
  test_matrix_1.matrix[1][1] = 5.0;
  test_matrix_1.matrix[2][0] = 3.0;
  test_matrix_1.matrix[2][1] = 6.0;

  test_matrix_3.matrix[0][0] = 1.0;
  test_matrix_3.matrix[0][1] = 2.0;
  test_matrix_3.matrix[0][2] = 3.0;
  test_matrix_3.matrix[1][0] = 4.0;
  test_matrix_3.matrix[1][1] = 5.0;
  test_matrix_3.matrix[1][2] = 6.0;

  s21_transpose(&test_matrix_1, &test_matrix_2);
  int eq = s21_eq_matrix(&test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(eq, SUCCESS);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(transpose_2) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 2, &test_matrix_1);
  s21_create_matrix(2, 3, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 4.0;
  test_matrix_1.matrix[1][0] = 2.0;
  test_matrix_1.matrix[1][1] = 5.0;
  test_matrix_1.matrix[2][0] = 3.0;
  test_matrix_1.matrix[2][1] = 6.0;

  test_matrix_3.matrix[0][0] = 1.0;
  test_matrix_3.matrix[0][1] = 2.0;
  test_matrix_3.matrix[0][2] = 3.0;
  test_matrix_3.matrix[1][0] = 4.0;
  test_matrix_3.matrix[1][1] = 5.0;
  test_matrix_3.matrix[1][2] = 6.0;

  int res = s21_transpose(NULL, &test_matrix_2);
  ck_assert_int_eq(res, MATRIX_ERROR);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(calc_complements_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(3, 3, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 0.0;
  test_matrix_1.matrix[1][1] = 4.0;
  test_matrix_1.matrix[1][2] = 2.0;
  test_matrix_1.matrix[2][0] = 5.0;
  test_matrix_1.matrix[2][1] = 2.0;
  test_matrix_1.matrix[2][2] = 1.0;

  test_matrix_3.matrix[0][0] = 0.0;
  test_matrix_3.matrix[0][1] = 10.0;
  test_matrix_3.matrix[0][2] = -20.0;
  test_matrix_3.matrix[1][0] = 4.0;
  test_matrix_3.matrix[1][1] = -14.0;
  test_matrix_3.matrix[1][2] = 8.0;
  test_matrix_3.matrix[2][0] = -8.0;
  test_matrix_3.matrix[2][1] = -2.0;
  test_matrix_3.matrix[2][2] = 4.0;

  int res = s21_calc_complements(&test_matrix_1, &test_matrix_2);
  int eq = s21_eq_matrix(&test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(eq, SUCCESS);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(calc_complements_2) {
  matrix_t *test_matrix_1 = NULL;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_2);
  s21_create_matrix(3, 3, &test_matrix_3);

  test_matrix_3.matrix[0][0] = 0.0;
  test_matrix_3.matrix[0][1] = 10.0;
  test_matrix_3.matrix[0][2] = -20.0;
  test_matrix_3.matrix[1][0] = 4.0;
  test_matrix_3.matrix[1][1] = -14.0;
  test_matrix_3.matrix[1][2] = 8.0;
  test_matrix_3.matrix[2][0] = -8.0;
  test_matrix_3.matrix[2][1] = -2.0;
  test_matrix_3.matrix[2][2] = 4.0;

  int res = s21_calc_complements(test_matrix_1, &test_matrix_2);
  int eq = s21_eq_matrix(&test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(eq, FAILURE);
  ck_assert_int_eq(res, MATRIX_ERROR);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

START_TEST(determinant_1) {
  matrix_t test_matrix_1;
  double test_num_1;
  double result_num = 0.0;
  s21_create_matrix(3, 3, &test_matrix_1);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 2.0;
  test_matrix_1.matrix[0][2] = 3.0;
  test_matrix_1.matrix[1][0] = 4.0;
  test_matrix_1.matrix[1][1] = 5.0;
  test_matrix_1.matrix[1][2] = 6.0;
  test_matrix_1.matrix[2][0] = 7.0;
  test_matrix_1.matrix[2][1] = 8.0;
  test_matrix_1.matrix[2][2] = 9.0;

  int res = s21_determinant(&test_matrix_1, &test_num_1);

  ck_assert_double_eq(test_num_1, result_num);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(determinant_2) {
  matrix_t test_matrix_1;
  double test_num_1;
  double result_num = 89.0;
  s21_create_matrix(2, 2, &test_matrix_1);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = -4.0;
  test_matrix_1.matrix[1][0] = 21.0;
  test_matrix_1.matrix[1][1] = 5.0;

  int res = s21_determinant(&test_matrix_1, &test_num_1);

  ck_assert_double_eq(test_num_1, result_num);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(determinant_3) {
  matrix_t test_matrix_1;
  double test_num_1;
  double result_num = -666.0;
  s21_create_matrix(1, 1, &test_matrix_1);

  test_matrix_1.matrix[0][0] = -666.0;

  int res = s21_determinant(&test_matrix_1, &test_num_1);

  ck_assert_double_eq(test_num_1, result_num);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(determinant_4) {
  matrix_t test_matrix_1;
  double test_num_1;
  s21_create_matrix(2, 1, &test_matrix_1);

  test_matrix_1.matrix[0][0] = -666.0;

  int res = s21_determinant(&test_matrix_1, &test_num_1);

  ck_assert_int_eq(res, CALC_ERROR);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(determinant_5) {
  matrix_t test_matrix_1;
  double test_num_1;
  double result_num = -191.0;
  s21_create_matrix(4, 4, &test_matrix_1);

  test_matrix_1.matrix[0][0] = 1.0;
  test_matrix_1.matrix[0][1] = 4.0;
  test_matrix_1.matrix[0][2] = 5.0;
  test_matrix_1.matrix[0][3] = 6.0;
  test_matrix_1.matrix[1][0] = 4.0;
  test_matrix_1.matrix[1][1] = 1.0;
  test_matrix_1.matrix[1][2] = 5.0;
  test_matrix_1.matrix[1][3] = 2.0;
  test_matrix_1.matrix[2][0] = 1.0;
  test_matrix_1.matrix[2][1] = 2.0;
  test_matrix_1.matrix[2][2] = 4.0;
  test_matrix_1.matrix[2][3] = 5.0;
  test_matrix_1.matrix[3][0] = 3.0;
  test_matrix_1.matrix[3][1] = 7.0;
  test_matrix_1.matrix[3][2] = 1.0;
  test_matrix_1.matrix[3][3] = 6.0;

  int res = s21_determinant(&test_matrix_1, &test_num_1);

  ck_assert_double_eq(test_num_1, result_num);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
}
END_TEST

START_TEST(inverse_matrix_1) {
  matrix_t test_matrix_1;
  matrix_t test_matrix_2;
  matrix_t test_matrix_3;
  s21_create_matrix(3, 3, &test_matrix_1);
  s21_create_matrix(3, 3, &test_matrix_3);

  test_matrix_1.matrix[0][0] = 2.0;
  test_matrix_1.matrix[0][1] = 5.0;
  test_matrix_1.matrix[0][2] = 7.0;
  test_matrix_1.matrix[1][0] = 6.0;
  test_matrix_1.matrix[1][1] = 3.0;
  test_matrix_1.matrix[1][2] = 4.0;
  test_matrix_1.matrix[2][0] = 5.0;
  test_matrix_1.matrix[2][1] = -2.0;
  test_matrix_1.matrix[2][2] = -3.0;

  test_matrix_3.matrix[0][0] = 1.0;
  test_matrix_3.matrix[0][1] = -1.0;
  test_matrix_3.matrix[0][2] = 1.0;
  test_matrix_3.matrix[1][0] = -38.0;
  test_matrix_3.matrix[1][1] = 41.0;
  test_matrix_3.matrix[1][2] = -34.0;
  test_matrix_3.matrix[2][0] = 27.0;
  test_matrix_3.matrix[2][1] = -29.0;
  test_matrix_3.matrix[2][2] = 24.0;

  int res = s21_inverse_matrix(&test_matrix_1, &test_matrix_2);

  int eq = s21_eq_matrix(&test_matrix_2, &test_matrix_3);
  ck_assert_int_eq(eq, SUCCESS);
  ck_assert_int_eq(res, OK);
  s21_remove_matrix(&test_matrix_1);
  s21_remove_matrix(&test_matrix_2);
  s21_remove_matrix(&test_matrix_3);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, create_matrix_1_OK);
  tcase_add_test(tc1_1, create_matrix_2_wrong_size_1);
  tcase_add_test(tc1_1, create_matrix_3_wrong_size_2);
  tcase_add_test(tc1_1, create_matrix_4_edge_values);
  tcase_add_test(tc1_1, remove_matrix_1);
  tcase_add_test(tc1_1, eq_matrix_1);
  tcase_add_test(tc1_1, eq_matrix_2);
  tcase_add_test(tc1_1, eq_matrix_3);
  tcase_add_test(tc1_1, sum_matrix_1);
  tcase_add_test(tc1_1, sum_matrix_2);
  tcase_add_test(tc1_1, sum_matrix_3);
  tcase_add_test(tc1_1, sub_matrix_1);
  tcase_add_test(tc1_1, sub_matrix_2);
  tcase_add_test(tc1_1, sub_matrix_3);
  tcase_add_test(tc1_1, mult_number_1);
  tcase_add_test(tc1_1, mult_number_2);
  tcase_add_test(tc1_1, mult_number_3);
  tcase_add_test(tc1_1, mult_matrix_1);
  tcase_add_test(tc1_1, mult_matrix_2);
  tcase_add_test(tc1_1, mult_matrix_3);
  tcase_add_test(tc1_1, transpose_1);
  tcase_add_test(tc1_1, transpose_2);
  tcase_add_test(tc1_1, calc_complements_1);
  tcase_add_test(tc1_1, calc_complements_2);
  tcase_add_test(tc1_1, determinant_1);
  tcase_add_test(tc1_1, determinant_2);
  tcase_add_test(tc1_1, determinant_3);
  tcase_add_test(tc1_1, determinant_4);
  tcase_add_test(tc1_1, determinant_5);
  tcase_add_test(tc1_1, inverse_matrix_1);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
